package test_tools

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"sync"
	"testing"
	"testing/synctest"
	"time"

	"github.com/LuckyGuessServices/planets/internal/databases"
	"github.com/LuckyGuessServices/planets/internal/env"
	"github.com/LuckyGuessServices/planets/internal/general"
	"github.com/LuckyGuessServices/planets/internal/integration/mercury"
	"github.com/LuckyGuessServices/planets/internal/luglog"
	pathsgeneral "github.com/LuckyGuessServices/planets/internal/paths/general"
	"github.com/LuckyGuessServices/planets/internal/shutdown_cleanup"
	"github.com/gofrs/flock"
)

func RunTestMain(m *testing.M) {
	testsRunExitCode := 9999
	defer func() {
		shutdown_cleanup.ExecuteStack()

		os.Exit(testsRunExitCode)
	}()

	setUpPackage()

	testsRunExitCode = m.Run()
}

// setUpPackage prepares the environment for each package,
// e.g. happens for each test subprocess generated by `go test`.
func setUpPackage() {
	var once sync.Once
	once.Do(func() {
		enforceEnvVars()
		env.PanicIfEnvNotTest()

		setUpGlobal()

		// Do NOT open the actual pool between tests. Most tests are executed within a "synced bubble"
		// ([synctest.Test]), and a db pool creation generates goroutines. If those goroutines are not created within
		// a test "bubble", calling [synctest.Wait] will fail affected tests.
		databases.EnableTestPools()
	})
}

// setUpGlobal prepares the "outer" environment (like a database initial contents) globally for all packages at once,
// e.g. happens once per `go test` launch, no matter how many packages are tested in subprocesses.
func setUpGlobal() {
	var once sync.Once
	once.Do(func() {
		fileLockPath := filepath.Join(os.TempDir(), fmt.Sprintf("%s-%d-test.lock", general.ServiceName, os.Getppid()))
		fileDonePath := fileLockPath + ".done"
		isAlreadyDoneFunc := func() bool {
			_, err := os.Stat(fileDonePath)

			return !errors.Is(err, os.ErrNotExist)
		}

		// No need to acquire a lock, if the job has been done already:
		if isAlreadyDoneFunc() {
			return
		}

		fileLock := flock.New(fileLockPath)
		if err := fileLock.Lock(); err != nil {
			// If OS physically prevents from creating the lock file (e.g., disk full, permissions error).
			luglog.Panicf("Failed to obtain '%s' file lock during global setup: %v", fileLockPath, err)
		}
		defer func() {
			if err := fileLock.Unlock(); err != nil {
				luglog.Panicf("Failed to release '%s' file lock after global setup: %v", fileLockPath, err)
			}
		}()

		// Again, no need to go further, if at this moment a parallel test subprocess has already done the job.
		if isAlreadyDoneFunc() {
			return
		}

		recreateTestDatabase()
		databases.MigrateUp()

		// Indicate the job should not be repeated:
		if err := os.WriteFile(fileDonePath, []byte(time.Now().Format(time.RFC3339Nano)), 0o600); err != nil {
			luglog.Panicf("Failed to create '%s' file marker after global setup: %v", fileDonePath, err)
		}
	})
}

func enforceEnvVars() {
	setEnvVar(env.VarNameApplicationEnvironment, string(env.ApplicationEnvironmentTest))
}

func recreateTestDatabase() {
	// CONFIG AND VARS ->

	envConfig := env.Config()
	dbConfig := databases.NewDBPrimaryConfig()
	dbConfig.DBName = envConfig.DBCoreRootDatabaseName()
	dbConfig.UserName = envConfig.DBCoreRootUsername()
	dbConfig.UserPassword = envConfig.DBCoreRootPassword()

	logPrefix := fmt.Sprintf("[DB 'CORE'; PPID %d]", os.Getppid())
	dbCoreRoot := databases.OpenAndPing(databases.DBPrimaryDriverName, dbConfig.DSN(), dbConfig.DSNForLogs())
	defer func() {
		if err := dbCoreRoot.Close(); err != nil {
			luglog.Panicf("%s Failed to close 'root' pool: %v", logPrefix, err)
		}
		luglog.Printf("%s 'root' pool is closed.", logPrefix)
	}()
	luglog.Printf("%s 'root' pool is initialized: %s", logPrefix, dbConfig.DSNForLogs())

	// <- CONFIG AND VARS

	// DATABASE RECREATION:

	_, errTerminateConnections := dbCoreRoot.Exec(
		fmt.Sprintf(
			`
				SELECT pg_terminate_backend(pg_stat_activity.pid)
				FROM pg_stat_activity
				WHERE pg_stat_activity.datname = '%s' AND pid <> pg_backend_pid()
			`,
			envConfig.DBCoreDatabaseName(),
		),
	)
	if errTerminateConnections != nil {
		luglog.Panicf(
			"%s Failed to terminate existing connections to database '%s': %v",
			logPrefix,
			envConfig.DBCoreDatabaseName(),
			errTerminateConnections,
		)
	}

	_, errDropDatabase := dbCoreRoot.Exec(
		fmt.Sprintf("DROP DATABASE IF EXISTS \"%s\"", envConfig.DBCoreDatabaseName()),
	)
	if errDropDatabase != nil {
		luglog.Panicf("%s Failed to drop database '%s': %v", logPrefix, envConfig.DBCoreDatabaseName(), errDropDatabase)
	}

	_, errCreateDatabase := dbCoreRoot.Exec(
		fmt.Sprintf("CREATE DATABASE \"%s\" OWNER \"%s\"", envConfig.DBCoreDatabaseName(), envConfig.DBCoreUsername()),
	)
	if errCreateDatabase != nil {
		luglog.Panicf(
			"%s Failed to create database '%s' owned by user '%s': %v",
			logPrefix,
			envConfig.DBCoreDatabaseName(),
			envConfig.DBCoreUsername(),
			errCreateDatabase,
		)
	}

	luglog.Printf("%s Database '%s' is recreated.", logPrefix, envConfig.DBCoreDatabaseName())
}

func setEnvVar(envVarName string, newValue string) {
	if err := os.Setenv(envVarName, newValue); err != nil {
		luglog.Panicf(
			"Failed to set env var '%s' to '%v': %v",
			envVarName,
			newValue,
			err,
		)
	}
}

// RunInSyncBubble ensures testFunction execution inside an isolated goroutines bubble with mocked time
// and hanging database pools being closed at the end of that bubble execution.
//
// If testFunction eventually produces goroutines, it should include [synctest.Wait] call to wait until all goroutines
// finish their execution.
func RunInSyncBubble(t *testing.T, testFunction func(t *testing.T)) {
	synctest.Test(t, func(t *testing.T) {
		defer func() {
			t.Helper()

			// Ensure to unset a mocked API client (if present).
			mercury.UnsetClientForTests()

			// Close the database pool:
			if _, err := databases.CloseCore(); err != nil {
				luglog.Panic("[DB] Failed to close CORE(TxDB) pool: ", err)
			}
			// No need to close readonly pool - in tests it is replaced with the same "master" writeable pool.
			// Otherwise, each such test launched within this helper will just fail.

			if panicVal := recover(); panicVal != nil {
				panicPackage, panicFile := pathsgeneral.PanicSource()
				panicString := fmt.Sprintf(
					"%#v; paniced function: %s\npanicked path: %s",
					panicVal,
					panicPackage,
					panicFile,
				)
				t.Fatal("Test general failure due to panic:", panicString)
			}
		}()

		testFunction(t)
	})
}
